In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [13]:
import pandas as pd
from sklearn.linear_model import LogisticRegression

data = pd.read_csv("data/Default.csv")
X = data[["income", "balance", "student"]]
y = data["default"]

model = LogisticRegression()
model.fit(X, y)
print(model.intercept_, model.coef_)

[-10.9018116] [[ 3.96189932e-06  5.73060606e-03 -6.12564504e-01]]


In [ ]:
x = pd.DataFrame({"income": [10000, 10000], "balance": [1950, 1950], "student": [1, 0]})
model.predict(x)

array([0, 1])

In [17]:
model.predict_proba(x).argmax(axis=1)

array([0, 1])

In [24]:
assert all(model.predict_proba(X).argmax(axis=1) == model.predict(X))

```
  array([[0.57446092, 0.42553908],
       [0.42250727, 0.57749273]])
  ```

In [29]:
p_student = 0.42553908
p_nonstudent = 0.57749273

o_student = p_student / (1 - p_student)
o_nonstudent = p_nonstudent / (1 - p_nonstudent)

print(o_student / o_nonstudent)

assert np.isclose(np.log(o_student / o_nonstudent), model.coef_.squeeze()[-1])

0.5419592408553978


In [ ]:
np.log(o_student / o_nonstudent)

np.float64(-0.6125644817440606)

In [27]:
model.coef_

array([[ 3.96189932e-06,  5.73060606e-03, -6.12564504e-01]])